version: '3'

services:
  infra-terraform:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/deploy/terraform_repo/
    env_file:
      - .env
    environment:
      CI_PROJECT_DIR: /build
      AWS_DEFAULT_REGION: ap-southeast-1
      CI_API_V4_URL: https://gitlab.com/api/v4
      GITLAB_PROJECT_ID: 
      CI_PROJECT_ID: 
    command: export TF_ADDRESS=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_VAR_app_name}-${TF_VAR_app_namespace}-${TF_VAR_tfenv} && \ 
             terraform init \
            -backend-config="address=${TF_ADDRESS}" \
            -backend-config="lock_address=${TF_ADDRESS}/lock" \
            -backend-config="unlock_address=${TF_ADDRESS}/lock" \
            -backend-config="username=${TF_VAR_gitlab_username}" \
            -backend-config="password=${TF_VAR_gitlab_token}" \
            -backend-config="lock_method=POST" \
            -backend-config="unlock_method=DELETE" \
            -backend-config="retry_wait_min=5"